### PR TITLE
setup subscription service to make request to notification service using rabbitMQ

### PR DESCRIPTION
**Pull request by alahirajeffrey**

### CODE REVIEW

**Review by Chimexx — CHANGES_REQUESTED** [review]
I checked your PR in notification service, you have a few endpoints with different patterns to receive events, like 'subscription', 'apiHosted' etc. But I can't fine where those patterns are emitted from in core service. Patterns should exist for both sender and receiver.

**Comment by alahirajeffrey** [comment]
As of now we are not notifying users concerning those other patterns. I just changes them from request methods to patterns so we would not have to do it when we are to start notifying users concerning that.

**Comment by alahirajeffrey** [comment]
Can you explain yourself.

The event patterns such as "subscription" are on the notify service. The core service can then emit to that particular pattern on the notify service for example when a user subscribes.

**Comment by Chimexx** [comment]
> Can you explain yourself.
> 
> The event patterns such as "subscription" are on the notify service. The core service can then emit to that particular pattern on the notify service for example when a user subscribes. 

Yes, how about other ones that are not on  available in core service?

**Comment by alahirajeffrey** [comment]
They would be available with time. This task was assigned specifically for subscription. I'll talk to @PhilemonBrain in the standup today about implementing the remaining patterns we have on the notification service on the core service.

**Pull request merged**
