### PR TITLE
Feature/create api architecture

### PR DESCRIPTION
**Pull request by Oladimejiibitoye**
This includes module structure( controller, service, etc files)

### CODE REVIEW

**Review by TijanAyo — COMMENTED** [review]
LGTM

But there is something I don't get... i can't seem to find any difference in the commit you made last 8 days and today's own

**Comment by Oladimejiibitoye** [comment]
> LGTM
> 
> But there is something I don't get... i can't seem to find any difference in the commit you made last 8 days and today's own

**Comment by Oladimejiibitoye** [comment]
I thought I pushed 8 days ago. Just find out I didnt

**Comment by TijanAyo** [comment]
Alright... 

- [ ] - Another thing is that I could not find the DTO directory
- [ ] - Also check if there is an API entity created if not add one

**Comment by Oladimejiibitoye** [comment]
> Alright...
> 
> * [ ]  - Another thing is that I could not find the DTO directory
 DTO would be created only if required
> * [ ]  - Also check if there is an API entity created if not... also add that
API entity already created

**Review by TijanAyo — COMMENTED** [review]
Please fix the conflict

**Review by TijanAyo — APPROVED** [review]

**Comment by Oladimejiibitoye** [comment]
conflict resolved

**Review by johnayinde — APPROVED** [review]

**Review by PhilemonBrain — APPROVED** [review]

**Pull request merged**
