### PR TITLE
Feature/id check guard

### PR DESCRIPTION
**Pull request by Oladimejiibitoye**
Id Check Guard takes an Id and checks if the Id is present in an existing database.

### CODE REVIEW

**Comment by johnayinde** [comment]
@Oladimejiibitoye 
since there's a way of checking all  IDs before getting to the service,  what about the  If..else condition in the services that is still serving the same purpose

**Comment by PhilemonBrain** [comment]
@johnayinde the idea if that those if elses would be removed, so our code is cleaner and elegant. 
So You need to test this feature and ensure it works fine... afterwards you'll be responsible for removing those if else checks in some of the modules

**Comment by johnayinde** [comment]
@Oladimejiibitoye fix the conflict

**Comment by Oladimejiibitoye** [comment]
Noted

**Review by PhilemonBrain — APPROVED** [review]

**Pull request merged**
