### PR TITLE
created endpoints to get a single feedback and a single contactUs

### PR DESCRIPTION
**Pull request by hayzedDev**

### CODE REVIEW

**Review by Chimexx — CHANGES_REQUESTED** [review]
I can't get the server running on your branch, it doesn't connect to my db, and it has to do with your changes in the ormconfig file. I told you not to do anything in that file, yet you did.

**Comment by hayzedDev** [comment]
When i was working on it, my db wasn't able to connect with the app. I only made ormconfig point to the environment variables.
image

I'll revert the changes and make another commit.

**Comment by hayzedDev** [comment]
@Chimexx Please review again

**Comment by Chimexx** [comment]
> When i was working on it, my db wasn't able to connect with the app. I only made ormconfig point to the environment variables. image
> 
> I'll revert the changes and make another commit.

If you have issues with the repo, it has to be something perculier to your setup. We can't change the setup because of that.

**Review by PhilemonBrain — APPROVED** [review]

**Pull request merged**
